### ISSUE TITLE
Y4000 Not sending correct responses

### ISSUE THREAD

**Issue by TzionCastillo1** [EnviroDIY/YosemitechModbus#23]
Hi,

I am attempting to connect a Y4000 to my Mayfly using a RS485-TTL adapter with automatic flow control. Using this library's GetValues example sketch, I am getting the following output on the Serial Monitor. It seems the sensor is sending its responses in a way that does not comply with their manual(see screenshot below) . Any help with this is appreciated.
![image](https://user-images.githubusercontent.com/31801540/154332642-204aef16-3c07-4518-8958-6eed1a5b1507.png)

-Tzion

**Comment by aufdenkampe** [comment]
Have you confirmed that the Modbus Address is correctly set in the sketch?

How did you Get or Set the Modbus address on the Y4000? The software from YosemiTech uses integer data types, but the sketches in this library all use the hexadecimal byte representation. These are only similar for addresses 0 to 9. That sometimes causes confusion and conflicts.

**Comment by TzionCastillo1** [comment]
I have it set to 0x01, from what I've read this has seemed like the default address.

**Comment by TzionCastillo1** [comment]
Update: It seems my issue was my power supply was causing the Y4000 to brown out.
Thank your for the help!
