### ISSUE TITLE
Problem - No communication with Y514 Chlorophyll sensor with brush

### ISSUE THREAD

**Issue by primus192** [EnviroDIY/YosemitechModbus#35]
Hello. I am new to this sensors. We ordered DO, Conductivity, pH, Depth, and Chlorophyll sensor.

All of this sensors are working great at variety of voltages 5-12V except chlorophyll. I can't get any output from this sensor, no version, no serial number, no measurements, nothing.
Chlorophyll (not working):
<img width="367" alt="image" src="https://github.com/EnviroDIY/YosemitechModbus/assets/89576620/f2c99a78-29da-4f42-b980-88fc84d912da">
Conductivity (working):
<img width="599" alt="image" src="https://github.com/EnviroDIY/YosemitechModbus/assets/89576620/e2973526-cba2-4f43-93dc-bfe2c1eb0853">

I am using our dedicated ESP32 board with rs485 adapter with DE, RE pins. I tried to adjust voltage from 5-12V, no luck. All grounds are common and connected together.

My sensor has HW 1.0 and SW 1.7 so i assume it is quite new. I reached out to Zoe from yosemitech. She sent me smart PC(2.6) software (a.k.a. Modbus runner?) and she told me to use USB-RS485 adapter so i bought one.

Strangely this chlorophyll sensor is working great with this USB-RS485 adapter even when I'm powering this sensor directly from it. I can read measurements, set, get, brush timings and manually activate brush.

![obraz_2023-06-15_123534527](https://github.com/EnviroDIY/YosemitechModbus/assets/89576620/0c031707-152b-462f-b78a-29c26db04e65)

![354382064_788866362945998_8535684306460279624_n](https://github.com/EnviroDIY/YosemitechModbus/assets/89576620/c12e83f0-fb6b-4490-91d1-1a7d9e3ecd77)

There comes my question. What can i do to make this sensor work with my board? Change RS485 adapter to auto-direction controlled one? Add capacitors? Maybe someone had same problem here @SRGDamia1  @aufdenkampe ? I am attaching some pictures for reference.

**Comment by SRGDamia1** [comment]
I've had much better luck in general with auto-direction RS485 adapters, but I don't have any experience with the chlorophyll sensor.

**Comment by primus192** [comment]
> I've had much better luck in general with auto-direction RS485 adapters, but I don't have any experience with the chlorophyll sensor.

Thank you for Your attention. I have already ordered auto direction adapters to test that. I will get back with results when i test it although it is strange that other sensors are working fine on standard adapters but not chlorophyll.

**Comment by primus192** [comment]
Ok my auto-direction RS485 adapter. It is working now. Closing as completed.
