### ISSUE TITLE
Add support for Y4000 Multi-Parameter Sonde

### ISSUE THREAD

**Issue by aufdenkampe** [EnviroDIY/YosemitechModbus#6]
I need to get this working by mid-March.
Here's the Modbus Manual: 
https://github.com/EnviroDIY/YosemitechModbus/blob/master/doc/Y4000-Sonde-1.6-ModbusInstruction-en.pdf

It appears to have very similar functions, but GetValues returns floats for all possible probes in a single response, returning 0 if a probe of a given type is not connected.

It's confusing how GetSN works, as it states that "Each sensor probe has a unique SN.", but the example response frame one has one shown. It appears the the SlaveID is for the sonde, not for the different probes connected to the sonde.

There are new set of functions, including:
* get/set real clock time
* Get supply voltage

**Comment by SRGDamia1** [comment]
Unfortunately, I don't have one of these to test and will have very little time to help with this unless you convince Arscott otherwise.

**Comment by aufdenkampe** [comment]
Largely done with PR #12, but still need:
* some utility functions have not yet been completed for Y4000
* Better documentation for Y4000

**Comment by aufdenkampe** [comment]
Closing this, as we mostly figured it out and also still have issue #13 open.
